//
//  Pairing.swift
//  AIUsage (shared)
//
//  Parses/validates the pairing string, derives the slot id / tokens / encryption key, and keeps the
//  pairing in the Keychain (shared access group so the widget extension can read it).
//
//  docs/PHONE-SYNC.md:
//    aiusage://pair?v=1&r=<percent-encoded relay base URL>&k=<base64url(K), no padding>
//    slotId     = hex(SHA256("aiusage-slot"  ‖ K))[0:32]
//    writeToken = hex(SHA256("aiusage-write" ‖ K))
//    readToken  = hex(SHA256("aiusage-read"  ‖ K))
//    encKey     =     SHA256("aiusage-enc"   ‖ K)   (32 raw bytes, AES-256-GCM)
//

import Foundation
import CryptoKit
import Security

// MARK: - Errors

enum PairingError: Error, LocalizedError, Equatable {
    case notAPairingLink
    case unsupportedVersion
    case missingRelay
    case invalidRelay
    case missingKey
    case invalidKey
    case keychain(OSStatus)
    case corruptStoredPairing

    var errorDescription: String? {
        switch self {
        case .notAPairingLink:
            return "That is not an AI Usage pairing code (expected aiusage://pair?…)."
        case .unsupportedVersion:
            return "This pairing code uses a protocol version this app does not understand (expected v=1)."
        case .missingRelay:
            return "The pairing code has no relay URL."
        case .invalidRelay:
            return "The relay URL is invalid — it must be https:// (http:// only for localhost)."
        case .missingKey:
            return "The pairing code has no key."
        case .invalidKey:
            return "The pairing key is malformed — it must decode to exactly 32 bytes."
        case .keychain(let status):
            if status == errSecMissingEntitlement {
                return "Keychain error -34018: the app group “group.com.aidanfl.aiusage” is missing from the provisioning profile (enable App Groups for both targets)."
            }
            return "Keychain error \(status)."
        case .corruptStoredPairing:
            return "The stored pairing could not be read — pair again."
        }
    }
}

// MARK: - Pairing

struct Pairing: Equatable {
    /// Relay base URL, trailing slash stripped (e.g. https://aiusage-relay.example.workers.dev).
    let relayURL: URL
    /// K — 32 random bytes generated by the desktop. Never sent anywhere.
    let pairKey: Data

    init(relayURL: URL, pairKey: Data) {
        self.relayURL = relayURL
        self.pairKey = pairKey
    }

    // MARK: Derived values

    /// `hex(SHA256("aiusage-slot" ‖ K))[0:32]`
    var slotId: String { return String(Pairing.hexDigest(label: "aiusage-slot", key: pairKey).prefix(32)) }
    /// `hex(SHA256("aiusage-write" ‖ K))` — the phone never uses it, exposed for completeness/debugging.
    var writeToken: String { return Pairing.hexDigest(label: "aiusage-write", key: pairKey) }
    /// `hex(SHA256("aiusage-read" ‖ K))` — Bearer token for GET.
    var readToken: String { return Pairing.hexDigest(label: "aiusage-read", key: pairKey) }
    /// `SHA256("aiusage-enc" ‖ K)` — AES-256-GCM key.
    var encKey: SymmetricKey { return SymmetricKey(data: Pairing.digest(label: "aiusage-enc", key: pairKey)) }

    static func digest(label: String, key: Data) -> Data {
        var input = Data(label.utf8)
        input.append(key)
        let hash = SHA256.hash(data: input)
        return Data(hash)
    }

    static func hexDigest(label: String, key: Data) -> String {
        return hex(digest(label: label, key: key))
    }

    static func hex(_ data: Data) -> String {
        return data.map { String(format: "%02x", $0) }.joined()
    }

    // MARK: Parsing

    /// Parses and validates `aiusage://pair?v=1&r=…&k=…` (also accepts surrounding whitespace).
    static func parse(_ raw: String) throws -> Pairing {
        let trimmed = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty, let comps = URLComponents(string: trimmed) else { throw PairingError.notAPairingLink }
        guard let scheme = comps.scheme?.lowercased(), scheme == "aiusage" else { throw PairingError.notAPairingLink }
        let host = (comps.host ?? "").lowercased()
        let path = comps.path.lowercased()
        guard host == "pair" || path == "/pair" || path == "pair" else { throw PairingError.notAPairingLink }

        var params: [String: String] = [:]
        for item in comps.queryItems ?? [] {
            if params[item.name] == nil { params[item.name] = item.value ?? "" }
        }

        guard let v = params["v"], v == "1" else { throw PairingError.unsupportedVersion }
        guard let r = params["r"], !r.isEmpty else { throw PairingError.missingRelay }
        guard let k = params["k"], !k.isEmpty else { throw PairingError.missingKey }

        let relay = try normalizeRelay(r)
        guard let key = base64URLDecode(k), key.count == 32 else { throw PairingError.invalidKey }
        return Pairing(relayURL: relay, pairKey: key)
    }

    /// Validates a relay base URL: https (http only for localhost/127.0.0.1), a host, no query/fragment/credentials;
    /// strips trailing slashes.
    static func normalizeRelay(_ raw: String) throws -> URL {
        var s = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        while s.hasSuffix("/") { s.removeLast() }
        guard let comps = URLComponents(string: s),
              let scheme = comps.scheme?.lowercased(),
              let host = comps.host?.lowercased(), !host.isEmpty else {
            throw PairingError.invalidRelay
        }
        let isLocal = host == "localhost" || host == "127.0.0.1"
        guard scheme == "https" || (scheme == "http" && isLocal) else { throw PairingError.invalidRelay }
        guard comps.query == nil, comps.fragment == nil, comps.user == nil, comps.password == nil else {
            throw PairingError.invalidRelay
        }
        guard let url = URL(string: s) else { throw PairingError.invalidRelay }
        return url
    }

    /// base64url (RFC 4648 §5, no padding) → Data.
    static func base64URLDecode(_ s: String) -> Data? {
        var str = s.trimmingCharacters(in: .whitespacesAndNewlines)
            .replacingOccurrences(of: "-", with: "+")
            .replacingOccurrences(of: "_", with: "/")
        while str.hasSuffix("=") { str.removeLast() }
        switch str.count % 4 {
        case 2: str += "=="
        case 3: str += "="
        case 1: return nil
        default: break
        }
        return Data(base64Encoded: str)
    }

    static func base64URLEncode(_ data: Data) -> String {
        var s = data.base64EncodedString()
            .replacingOccurrences(of: "+", with: "-")
            .replacingOccurrences(of: "/", with: "_")
        while s.hasSuffix("=") { s.removeLast() }
        return s
    }

    /// Rebuilds the canonical pairing string (used by Settings to show/copy it).
    var pairString: String {
        var comps = URLComponents()
        comps.scheme = "aiusage"
        comps.host = "pair"
        comps.queryItems = [
            URLQueryItem(name: "v", value: "1"),
            URLQueryItem(name: "r", value: relayURL.absoluteString),
            URLQueryItem(name: "k", value: Pairing.base64URLEncode(pairKey)),
        ]
        return comps.string ?? "aiusage://pair"
    }
}

// MARK: - Keychain persistence

/// What is persisted (as JSON in a generic-password item).
private struct StoredPairing: Codable {
    var relay: String
    var k: String       // base64 (standard) of the 32-byte key
}

enum PairingStore {
    static let service = "com.aidanfl.aiusage.pairing"
    static let account = "default"
    /// On iOS an App Group id is a valid keychain access group (no team prefix).
    static let accessGroup = "group.com.aidanfl.aiusage"

    private static func baseQuery(useGroup: Bool) -> [String: Any] {
        var q: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: service,
            kSecAttrAccount as String: account,
        ]
        if useGroup { q[kSecAttrAccessGroup as String] = accessGroup }
        return q
    }

    /// Stores (replacing any previous value) the pairing in the shared keychain group.
    static func save(_ pairing: Pairing) throws {
        let stored = StoredPairing(relay: pairing.relayURL.absoluteString, k: pairing.pairKey.base64EncodedString())
        let data = try JSONEncoder().encode(stored)
        var status = write(data, useGroup: true)
        #if targetEnvironment(simulator)
        // Some simulator runtimes reject access groups (-34018) when the app is not signed with them;
        // fall back to the private keychain so development in the Simulator still works.
        if status == errSecMissingEntitlement { status = write(data, useGroup: false) }
        #endif
        guard status == errSecSuccess else { throw PairingError.keychain(status) }
    }

    private static func write(_ data: Data, useGroup: Bool) -> OSStatus {
        let deleteStatus = SecItemDelete(baseQuery(useGroup: useGroup) as CFDictionary)
        if deleteStatus != errSecSuccess && deleteStatus != errSecItemNotFound {
            return deleteStatus
        }
        var attrs = baseQuery(useGroup: useGroup)
        attrs[kSecValueData as String] = data
        attrs[kSecAttrAccessible as String] = kSecAttrAccessibleAfterFirstUnlock
        return SecItemAdd(attrs as CFDictionary, nil)
    }

    /// Loads the pairing; nil when nothing is stored.
    static func load() throws -> Pairing? {
        var result = read(useGroup: true)
        #if targetEnvironment(simulator)
        if case .failure(let status) = result, status == errSecMissingEntitlement { result = read(useGroup: false) }
        #endif
        switch result {
        case .success(let data):
            guard let data = data else { return nil }
            guard let stored = try? JSONDecoder().decode(StoredPairing.self, from: data),
                  let key = Data(base64Encoded: stored.k), key.count == 32,
                  let url = try? Pairing.normalizeRelay(stored.relay) else {
                throw PairingError.corruptStoredPairing
            }
            return Pairing(relayURL: url, pairKey: key)
        case .failure(let status):
            throw PairingError.keychain(status)
        }
    }

    private enum ReadResult {
        case success(Data?)
        case failure(OSStatus)
    }

    private static func read(useGroup: Bool) -> ReadResult {
        var q = baseQuery(useGroup: useGroup)
        q[kSecReturnData as String] = true
        q[kSecMatchLimit as String] = kSecMatchLimitOne
        var item: CFTypeRef?
        let status = SecItemCopyMatching(q as CFDictionary, &item)
        if status == errSecItemNotFound { return .success(nil) }
        guard status == errSecSuccess else { return .failure(status) }
        return .success(item as? Data)
    }

    /// Removes the pairing (both the shared and, on the Simulator, the private copy). Never throws for "absent".
    static func clear() throws {
        let s1 = SecItemDelete(baseQuery(useGroup: true) as CFDictionary)
        #if targetEnvironment(simulator)
        _ = SecItemDelete(baseQuery(useGroup: false) as CFDictionary)
        #endif
        if s1 != errSecSuccess && s1 != errSecItemNotFound && s1 != errSecMissingEntitlement {
            throw PairingError.keychain(s1)
        }
    }
}
